/*
 * MODULE: MultiQC
 * Aggregates QC reports from all tools into a single HTML report
 */

process MULTIQC {

    label 'process_single'

    container 'quay.io/biocontainers/multiqc:1.21--pyhdfd78af_0'

    publishDir "${params.outdir}/qc/multiqc", mode: 'copy'

    input:
    path multiqc_files, stageAs: "?/*"

    output:
    path "*multiqc_report.html", emit: report
    path "*_data",               emit: data
    path "*_plots",              emit: plots, optional: true
    path "versions.yml",         emit: versions

    script:
    """
    multiqc \\
        --force \\
        --title "OmicsFlow RNA-seq QC Report" \\
        --comment "Generated by OmicsFlow v1.0.0 — Sory Millimono" \\
        .

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        multiqc: \$(multiqc --version | sed 's/multiqc, version //')
    END_VERSIONS
    """

    stub:
    """
    touch multiqc_report.html
    mkdir multiqc_data
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        multiqc: 1.21
    END_VERSIONS
    """
}
